### ISSUE TITLE
Fix display of gameboy action

### ISSUE THREAD

**Issue by mpefaur** [P4-Games/NofyGotchi#1]
Fix display gameboy. Hoy el tiempo de la animación no concuerda con el tiempo de ejecución de la acción jugar. Dado que el gif se ejecuta en bucle la idea es que el display dure lo mismo que el tiempo actual de la acción.

**Comment by tincho70** [comment]
Este bug se puede cerrar 😉

**Comment by mpefaur** [comment]
Genio! Fixeado, testeado y aprobado!
